// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlgoohuxuuancjtozncc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsZ29vaHV4dXVhbmNqdG96bmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDc1NDgsImV4cCI6MjA2OTgyMzU0OH0.xdxgKWa-oAeReLa2NfNLMryZFKsH_YicEuiIU7jDGdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});